dist: trusty
language: node_js
node_js:
  - "6"
services:
  - postgresql
before_script:
  - psql -c 'create database dms_test;' -U postgres
  - NODE_ENV=test npm run db:init
after_success:
  - npm run coveralls
