dist: trusty
language: node_js
node_js:
  - "6"
services:
  - postgresql
after_success:
  - npm run coveralls
before_script:
  - psql -c 'create database dms_test;' -U postgres
  - NODE_ENV=test ./node_modules/.bin/sequelize db:migrate
